POST http://localhost:8080/companies HTTP/1.1
content-type: application/json
{
    "id":123,
    "name":"jiale",
    "country":"bobo"
}


###
GET http://localhost:8080/companies HTTP/1.1

###
GET http://localhost:8080/companies HTTP/1.1###
Authorization: abcd